name: google_places_dialog
description: A Very Good Project created by Very Good CLI.
version: 0.2.0+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_debouncer: ^1.3.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
